### ISSUE TITLE
dynamic unpatching to reduce overhead

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#839]
I don't know how to call it - maybe dynamic unpatching or reverse dynamic.  Anyway it's about to disable tracing for already instrumented functions by compiler.  For example we can use dynamic tracing for a non-instrumented binary to trace selected functions only.  But it could not apply the same technique if functions already have mcount/fentry calls.  This change will do it by overwriting calls to NOPs if it doesn't match to the given pattern (the `-P` option).

For simplicity, it only supports two cases - binary with build `-pg -mfentry` or `-pg -mrecord-mcount` on x86_64.  And it doesn't use capstone for this. :)

```
$ gcc -pg -mfentry foo.c

$ uftrace --no-libcall a.out
# DURATION     TID     FUNCTION
            [ 84256] | main() {
            [ 84256] |   foo() {
   0.343 us [ 84256] |     bar();
   0.215 us [ 84256] |     bar();
   3.275 us [ 84256] |   } /* foo */
   7.549 us [ 84256] | } /* main */
```

Now run again with `-P` option, other functions will disappear.

```
$ u --no-libcall -P foo a.out
# DURATION     TID     FUNCTION
   1.339 us [ 85995] | foo();
```

I pushed the code to [review/dynamic-unpatch-v1](https://github.com/namhyung/uftrace/compare/review/dynamic-unpatch-v1).

**Comment by honggyukim** [comment]
Thanks a lot for doing this! I've tested this as follows:

**1. `-pg -mfentry`**
It works fine as expected.
```
$ gcc -pg -mfentry tests/s-abc.c 
$ uftrace -P b a.out 
# DURATION     TID     FUNCTION
   1.440 us [ 12319] | __monstartup();
   0.567 us [ 12319] | __cxa_atexit();
            [ 12319] | b() {
   0.529 us [ 12319] |   getpid();
   4.531 us [ 12319] | } /* b */
```
**2. `-pg -mrecord-mcount`**
However, it doesn't properly work as expected.
```
$ gcc -pg -mrecord-mcount tests/s-abc.c 
$ uftrace -P b a.out 
# DURATION     TID     FUNCTION
   2.206 us [ 12344] | __monstartup();
   0.717 us [ 12344] | __cxa_atexit();
            [ 12344] | main() {
            [ 12344] |   a() {
            [ 12344] |     b() {
            [ 12344] |       c() {
   0.464 us [ 12344] |         getpid();
   1.405 us [ 12344] |       } /* c */
   1.782 us [ 12344] |     } /* b */
   2.102 us [ 12344] |   } /* a */
   2.442 us [ 12344] | } /* main */
```
Unfortunately, it cannot be used for ARM/AArch64 due to the lacking compiler support.
```
$ arm-linux-gnueabihf-gcc --version | grep gcc
arm-linux-gnueabihf-gcc (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0

$ arm-linux-gnueabihf-gcc -pg -mfentry tests/s-abc.c
arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-mfentry’; did you mean ‘--entry’?

$ arm-linux-gnueabihf-gcc -pg -mrecord-mcount tests/s-abc.c
arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-mrecord-mcount’
```
```
$ aarch64-linux-gnu-gcc --version | grep gcc
aarch64-linux-gnu-gcc (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0

$ aarch64-linux-gnu-gcc -pg -mfentry tests/s-abc.c
aarch64-linux-gnu-gcc: error: unrecognized command line option ‘-mfentry’; did you mean ‘--entry’?

$ aarch64-linux-gnu-gcc -pg -mrecord-mcount tests/s-abc.c
aarch64-linux-gnu-gcc: error: unrecognized command line option ‘-mrecord-mcount’
```

**Comment by honggyukim** [comment]
I'm just wondering if it's not possible to unpatch `mcount` calls without `-mrecord-mcount`. I'm not sure if it's possible but we could try pattern patching for `mcount` calls.

**Comment by honggyukim** [comment]
In addition, I think it'd be useful to have `-U` for unpatching.

**Comment by namhyung** [comment]
We can unpatch `-pg` built binaries using capstone, will work on it later.  And ARM/AArch64 might be easier to handle since their instruction length is fixed.

**Comment by namhyung** [comment]
I'm not sure it's good to add an option for that.

**Comment by honggyukim** [comment]
> We can unpatch -pg built binaries using capstone, will work on it later. And ARM/AArch64 might be easier to handle since their instruction length is fixed.

Understood. Thanks.

> I'm not sure it's good to add an option for that.

It's to skip some specific functions and it can be used for different purposes from `-N` option.

**Comment by namhyung** [comment]
I'm thinking of just using `-P` option for that too.

Anyway, was your program built with `-pie`?  Please try this for the failed `-mrecord-mcount` case.

```diff
diff --git a/arch/x86_64/mcount-dynamic.c b/arch/x86_64/mcount-dynamic.c
index 7f8813c..c6d3317 100644
--- a/arch/x86_64/mcount-dynamic.c
+++ b/arch/x86_64/mcount-dynamic.c
@@ -236,6 +236,7 @@ void mcount_arch_find_module(struct mcount_dynamic_info *mdi,
        pr_dbg("dynamic patch type: %s: %d (%s)\n", basename(mdi->map->libname),
               adi->type, adi_type_names[adi->type]);
 
+       mdi->elf_type = elf.ehdr.e_type;
        mdi->arch = adi;
        elf_finish(&elf);
 }
@@ -586,7 +587,10 @@ static int unpatch_mcount_func(struct mcount_dynamic_info *mdi, struct sym *sym)
 
                if (loc != NULL) {
                        uint8_t *insn = (uint8_t*) *loc;
-                       return unpatch_func(insn + mdi->map->start, sym->name);
+
+                       if (mdi->elf_type == ET_DYN)
+                               insn += mdi->map->start;
+                       return unpatch_func(insn, sym->name);
                }
        }
 
diff --git a/libmcount/internal.h b/libmcount/internal.h
index e973675..02c4add 100644
--- a/libmcount/internal.h
+++ b/libmcount/internal.h
@@ -396,6 +396,7 @@ struct mcount_dynamic_info {
        unsigned long base_addr;
        unsigned long text_addr;
        int text_size;
+       int elf_type;
        unsigned long trampoline;
        void *arch;
 };
```

**Comment by honggyukim** [comment]
Hmm.. the result is still the same.
```
$ gcc -pg -mrecord-mcount tests/s-abc.c 
$ uftrace -P b a.out 
# DURATION     TID     FUNCTION
   1.525 us [ 20088] | __monstartup();
   0.578 us [ 20088] | __cxa_atexit();
            [ 20088] | main() {
            [ 20088] |   a() {
            [ 20088] |     b() {
            [ 20088] |       c() {
   0.473 us [ 20088] |         getpid();
   1.234 us [ 20088] |       } /* c */
   1.586 us [ 20088] |     } /* b */
   1.857 us [ 20088] |   } /* a */
   2.186 us [ 20088] | } /* main */
```
Here is the full configuration of gcc.
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.11' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)
```

**Comment by honggyukim** [comment]
Here is the code coverage info. It seems that it couldn't find the address location.
```c
          Line data    Source code
     628           5 : int mcount_unpatch_func(struct mcount_dynamic_info *mdi, struct sym *sym,
     629             :                         struct mcount_disasm_engine *disasm)
     630             : {
     631           5 :         struct arch_dynamic_info *adi = mdi->arch;
     632           5 :         int result = INSTRUMENT_SKIPPED;
     633             : 
     634           5 :         switch (adi->type) {
     635             :         case DYNAMIC_FENTRY:
     636           0 :                 result = unpatch_fentry_func(mdi, sym);
     637           0 :                 break;
     638             : 
     639             :         case DYNAMIC_PG:
     640           5 :                 result = unpatch_mcount_func(mdi, sym);
     641           5 :                 break;
     642             : 
     643             :         default:
     644           0 :                 break;
     645             :         }
     646           5 :         return result;
     647             : }

     578           5 : static int unpatch_mcount_func(struct mcount_dynamic_info *mdi, struct sym *sym)
     579             : {
     580           5 :         struct arch_dynamic_info *adi = mdi->arch;
     581             :         uintptr_t *loc;
     582             : 
     583           5 :         if (adi->nr_mcount_loc != 0) {
     584           5 :                 loc = bsearch(sym, adi->mcount_loc, adi->nr_mcount_loc,
     585             :                                sizeof(adi->mcount_loc), cmp_loc);
     586             : 
     587           5 :                 if (loc != NULL) {
     588           0 :                         uint8_t *insn = (uint8_t*) *loc;
     589           0 :                         return unpatch_func(insn + mdi->map->start, sym->name);
     590             :                 }
     591             :         }
     592             : 
     593           5 :         return INSTRUMENT_SKIPPED;
     594             : }

     567          15 : static int cmp_loc(const void *a, const void *b)
     568             : {
     569          15 :         const struct sym *sym = a;
     570          15 :         uintptr_t loc = *(uintptr_t *)b;
     571             : 
     572          15 :         if (sym->addr <= loc && loc < sym->addr + sym->size)
     573           0 :                 return 0;
     574             : 
     575          15 :         return sym->addr > loc ? 1 : -1;
     576             : }
```

**Comment by honggyukim** [comment]
Hmm.. It seems that the problem comes from `sym->addr` is relative address without applying map start address. I just printed the values inside `cmp_loc` for them and it looks as follows:
```
loc = 0x4006f0
sym->addr = 0x5b0
sym->size = 65
```

**Comment by namhyung** [comment]
Thanks for the info.  How about this?  (please don't apply the patch above)

```diff
diff --git a/arch/x86_64/mcount-dynamic.c b/arch/x86_64/mcount-dynamic.c
index 7f8813c..ae94c59 100644
--- a/arch/x86_64/mcount-dynamic.c
+++ b/arch/x86_64/mcount-dynamic.c
@@ -167,7 +167,14 @@ static void read_mcount_loc(struct arch_dynamic_info *adi,
        elf_get_secdata(elf, iter);
        elf_read_secdata(elf, iter, 0, adi->mcount_loc, shdr->sh_size);
 
-       /* do not add offset for mcount_loc (will do in unpatch_mcount_func) */
+       /* symbol has relative address, fix it to match each other */
+       if (elf->ehdr.e_type == ET_EXEC) {
+               unsigned i;
+
+               for (i = 0; i < adi->nr_mcount_loc; i++) {
+                       adi->mcount_loc[i] -= offset;
+               }
+       }
 }
 
 void mcount_arch_find_module(struct mcount_dynamic_info *mdi,
```

**Comment by honggyukim** [comment]
It works fine. Thanks!
```
$ gcc -pg -mrecord-mcount tests/s-abc.c
$ uftrace -P b a.out
# DURATION     TID     FUNCTION
   1.624 us [135481] | __monstartup();
   0.867 us [135481] | __cxa_atexit();
            [135481] | b() {
   0.890 us [135481] |   getpid();
   5.334 us [135481] | } /* b */
```

**Comment by honggyukim** [comment]
>>> In addition, I think it'd be useful to have -U for unpatching.

>> I'm not sure it's good to add an option for that.

> It's to skip some specific functions and it can be used for different purposes from -N option.

Otherwise, I hope that this unpatching is needed not only for dynamic tracing, but also general cases. Especially, I think it's very much needed when applying `-Z` size filter even without dynamic tracing.

**Comment by namhyung** [comment]
Pushed [review/dynamic-unpatch-v2](https://github.com/namhyung/uftrace/compare/review/dynamic-unpatch-v2)

Changelog:
 * fix `-mrecord-mcount` case
 * add `-U` option to add pattern for unpatch

**Comment by namhyung** [comment]
Yep, I'll try to update and merge it.

**Comment by namhyung** [comment]
Merged: 344d05bd
